package com.ljy.sbtemplate.model.po.sbt.mbg;

public class Temp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.id
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.name
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.id
     *
     * @return the value of temp.id
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.id
     *
     * @param id the value for temp.id
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.name
     *
     * @return the value of temp.name
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.name
     *
     * @param name the value for temp.name
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Thu Feb 14 17:31:25 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}